a<-c(1:6)
a
str(a)
a <- as.character(a)
s)r(a)
df <- data.frame(stu=c("a","b","c"), math=c(60, 70, 80))
str(df)
df$height <- c(176, 177, 178)
str(df)
library(dplyr)
df$weight <- c(60, 50, 80)
df <- df %>% mutate(bmi=df$weight/(df$height/100)^2)
str(df)
df2 <- as.list(df)
str(df)
str(df2)
df3 <- matrix(c(1:6), nrow=2, ncol=3)
str(df3)
df3
df4 <- matrix(c(1:6), nrow=2, ncol=3, byrow=TRUE)
df4
library(lubridate)
ymd("2025 12 11")
mdy("12 11 2025")
a<-make_date(2025,11,20)

b<-make_date(2025,12,20)
c<-difftime(a,b,units="days")
print(c)
temp<-airquality$Temp
z_temp<-scale(temp)
summary(z_temp)
minmax_temp<-scale(temp, min(temp), max(temp)-min(temp))
summary(minmax_temp)
str(iris)
data <- iris %>%
  group_by(Species)%>%summarise(mean(Petal.Length))
str(data)
data2 <- iris %>% select(-4,-5)
str(data2)
cor(data2)
cor(data2, method="pearson")

q1 <- quantile(temp, 0.25)
q3 <- quantile(temp, 0.75)
iqr <- abs(q3 - q1)
print(iqr)
table(iris$Species)
var(temp)^(1/2)
sd(temp)

library(LakeHuron)
lake <- sample(LakeHuron, 30, TRUE)
lake
talbe(lake)
talbe(lake)
table(lake)
x<- c(1,2,3,1,1,1,1,2,2,3,3,2,2,1)
table(x)
which.max(table(x))
names(table(x))[which.max(table(x))]
as.numeric(names(table(x))[which.max(table(x))])
