library(dplyr)
library(lubridate)
rdata <- read.csv("P220403.csv")
str(rdata)
rdata$date_added <- mdy(rdata$date_added)
str(rdata)
#data <- rdata %>% filter(year(date_added)==2018) %>% filter(month(date_added)==1) %>% filter(country=="United Kingdom")
nrow(data)
data <- rdata %>% filter(year(date_added)==2018 & month(date_added)==1 & country=="United Kingdom")
nrow(data)
