library(dplyr)
rdata <- read.csv("P220402.csv")
str(rdata)
colSums(is.na(rdata))
data <- rdata %>% mutate(pos=(num_loves+num_wows)/num_reactions)
str(data)
data1 <- data %>% filter(pos>0.4 & pos<0.5)
result <- nrow(data1)
print(result)
print(round(result))
